apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: fastapi-app
          image: rahuldocker25/fastapi-demo:v1
          ports:
            - containerPort: 5000